server:
  port: 8055

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: Distributed System Application
  devtools:
    livereload:
      enabled: false
    add-properties: false


kafka:
  consumer:
    groups:
      primary: primary
      secondary: secondary
  polling-size: 5
  partition-size: 1
  replication-factor: 1